# Generated by Django 5.1.4 on 2025-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_panier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
